items = {
    1: "smartphone",
    2: "laptop",
    3: "tablet",
    4: "4K monitor",
    5: "mechanical keyboard",
    6: "wireless mouse",
    7: "3D printer",
    8: "mesh Wi-Fi router",
    9: "true wireless earbuds",
    10: "4K webcam",
    11: "smartwatch",
    12: "VR headset",
    13: "wireless charger",
    14: "portable SSD",
    15: "gaming chair",
    16: "noise-cancelling headphones",
    17: "smart home hub",
    18: "drone",
    19: "smart glasses",
    20: "mechanical numpad"
}